import type { Env, GeneratedNugget, GitHubPRResponse } from './types';

export async function createPullRequest(
	nugget: GeneratedNugget,
	env: Env,
	scheduledFor?: string
): Promise<GitHubPRResponse> {
	const branchName = `${env.GITHUB_BRANCH_PREFIX}/${nugget.slug}-${Date.now()}`;
	const filePath = `src/content/nuggets/${nugget.slug}.mdx`;
	const [owner, repo] = env.GITHUB_REPO.split('/');

	// Get base branch SHA
	const baseBranch = 'master';
	const baseRefResponse = await githubAPI(
		`/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`,
		'GET',
		env.GITHUB_TOKEN
	);
	const baseSHA = baseRefResponse.object.sha;

	// Create new branch
	await githubAPI(`/repos/${owner}/${repo}/git/refs`, 'POST', env.GITHUB_TOKEN, {
		ref: `refs/heads/${branchName}`,
		sha: baseSHA,
	});

	// Get base tree
	const baseCommit = await githubAPI(
		`/repos/${owner}/${repo}/git/commits/${baseSHA}`,
		'GET',
		env.GITHUB_TOKEN
	);
	const baseTreeSHA = baseCommit.tree.sha;

	// Create blob for new file
	const blobResponse = await githubAPI(`/repos/${owner}/${repo}/git/blobs`, 'POST', env.GITHUB_TOKEN, {
		content: nugget.fullMdx,
		encoding: 'utf-8',
	});

	// Create new tree with the file
	const treeResponse = await githubAPI(`/repos/${owner}/${repo}/git/trees`, 'POST', env.GITHUB_TOKEN, {
		base_tree: baseTreeSHA,
		tree: [
			{
				path: filePath,
				mode: '100644',
				type: 'blob',
				sha: blobResponse.sha,
			},
		],
	});

	// Create commit
	const commitResponse = await githubAPI(
		`/repos/${owner}/${repo}/git/commits`,
		'POST',
		env.GITHUB_TOKEN,
		{
			message: `feat: add nugget "${nugget.frontmatter.title}"`,
			tree: treeResponse.sha,
			parents: [baseSHA],
		}
	);

	// Update branch reference
	await githubAPI(
		`/repos/${owner}/${repo}/git/refs/heads/${branchName}`,
		'PATCH',
		env.GITHUB_TOKEN,
		{
			sha: commitResponse.sha,
		}
	);

	// Create pull request
	const prResponse = await githubAPI(`/repos/${owner}/${repo}/pulls`, 'POST', env.GITHUB_TOKEN, {
		title: `✨ New Nugget: ${nugget.frontmatter.title}`,
		head: branchName,
		base: baseBranch,
		body: buildPRBody(nugget, scheduledFor),
	});

	return {
		prUrl: prResponse.html_url,
		prNumber: prResponse.number,
		branchName,
	};
}

function buildPRBody(nugget: GeneratedNugget, scheduledFor?: string): string {
	const scheduledInfo = scheduledFor ? `**Scheduled for:** ${scheduledFor} (publish after merge)` : '';
	
	return `## 🔥 New AI-Generated Nugget

**Title:** ${nugget.frontmatter.title}  
**Tags:** ${nugget.frontmatter.tags.join(', ')}  
**Word Count:** ~${nugget.content.split(/\s+/).length} words
${scheduledInfo ? `\n${scheduledInfo}\n` : ''}

### Review Checklist
- [ ] Technical accuracy verified
- [ ] No invented metrics or vendor claims
- [ ] Code examples ≤20 LOC and illustrative
- [ ] Tone: concise, senior IC, no fluff
- [ ] Tags appropriate

### Post-Merge
- [ ] Schedule LinkedIn post
- [ ] Include in Sunday newsletter digest

---
*Auto-generated by AI Worker | [View source](src/content/nuggets/${nugget.slug}.mdx)*`;
}

async function githubAPI(
	endpoint: string,
	method: 'GET' | 'POST' | 'PATCH',
	token: string,
	body?: any
): Promise<any> {
	const response = await fetch(`https://api.github.com${endpoint}`, {
		method,
		headers: {
			Accept: 'application/vnd.github.v3+json',
			Authorization: `Bearer ${token}`,
			'Content-Type': 'application/json',
			'User-Agent': 'farhan-dev-ai-worker',
		},
		body: body ? JSON.stringify(body) : undefined,
	});

	if (!response.ok) {
		const errorText = await response.text();
		throw new Error(`GitHub API error (${endpoint}): ${response.status} - ${errorText}`);
	}

	return response.json();
}

/**
 * Check if a PR has been merged
 */
export async function checkPRStatus(prNumber: number, env: Env): Promise<boolean> {
	const [owner, repo] = env.GITHUB_REPO.split('/');
	
	try {
		const prResponse = await githubAPI(
			`/repos/${owner}/${repo}/pulls/${prNumber}`,
			'GET',
			env.GITHUB_TOKEN
		);
		
		return prResponse.merged === true;
	} catch (error) {
		console.error(`Error checking PR #${prNumber}:`, error);
		return false;
	}
}
